/**
 * Twin CAD — LeKiwi kit mobile base (3-wheel omni, no arm)
 * + HouseHand torso · shoulder deck · neck · head · 2× SO-101.
 * Printables live in print/xlerobot/hardware/ (same STLs as public/assets).
 * No IKEA RÅSKOG cart / 4-wheel set (SIGRobotics / Vector-Wangel, Apache-2.0).
 */
import { useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react'
import { useLoader } from '@react-three/fiber'
import {
  Box3,
  BufferGeometry,
  DoubleSide,
  Group,
  LoadingManager,
  Mesh,
  MeshStandardMaterial,
  Object3D,
} from 'three'
import { STLLoader } from 'three/addons/loaders/STLLoader.js'
import URDFLoader, { type URDFRobot } from 'urdf-loader'
import type { Colourway } from '../product'
import { TELESCOPE } from '../robot/dims'
import { kitCaption, type KitBuild } from '../kit/catalog'
import { getPerfTier } from '../kit/perf'

const asset = (path: string) => `${import.meta.env.BASE_URL}${path.replace(/^\//, '')}`

const LEKIWI_URDF = asset('assets/lekiwi/LeKiwi.urdf')
const LEKIWI_PATH = asset('assets/lekiwi/')
const SO101_URDF = asset('assets/so101/so101_new_calib.urdf')
const SO101_PATH = asset('assets/so101/')
/** Printable structure kit — generated by scripts/gen_structure_kit.py (Ø180 / flange Ø190). */
const TORSO_STL = asset('assets/xlerobot/hardware/HouseHand_torso.stl')
const ARMBASE_STL = asset('assets/xlerobot/hardware/HouseHand_shoulder_deck.stl')
const NECK_STL = asset('assets/xlerobot/hardware/HouseHand_neck.stl')
const HEAD_MOUNT_STL = asset('assets/xlerobot/hardware/HouseHand_head_mount.stl')
const HEAD_CAM_STL = asset('assets/xlerobot/hardware/HouseHand_head_camera.stl')

/** LeKiwi: ROS Z-up → Three Y-up. */
const ROS_TO_THREE: [number, number, number] = [-Math.PI / 2, 0, Math.PI]
/** Shoulder pack / arms / head face rover-forward. */
const STACK_TO_THREE: [number, number, number] = [-Math.PI / 2, 0, Math.PI / 2]
const SIT_EPS = 0.0005
const PRINT_SCALE = 0.001
/**
 * Circular SO-101 pad centers on HouseHand_shoulder_deck (mm, print frame).
 * Locked with scripts/gen_structure_kit.py · cad/shoulder_deck.scad
 */
const MOUNT_PAD_X_MM = -26
const MOUNT_HALF_MM = 138
/**
 * Pad top Z after footGeometry (deck ring underside → Z=0).
 * ring 4 + plate 12 + pad 6 = 22 mm.
 */
const SHOULDER_PAD_TOP_MM = 22
/**
 * Yaw both arms in the print frame so the shared SO-101 pose faces rover-forward.
 * Side-view checks showed yaw 0 aimed aft; π aims grippers with the head/camera.
 */
const ARM_FORWARD_YAW = Math.PI
/** Undo PRINT_SCALE so meter-based SO-101 URDFs stay true-size inside the mm group. */
const ARM_IN_PRINT = 1 / PRINT_SCALE
/** Skip LeKiwi onboard arm + cam tower. Keep real omni wheels. */
const LEKIWI_SKIP_MESH =
  /Base_08|SO_ARM|Rotation_Pitch_08|Moving_Jaw|Passive_Horn|STS3215_03a|WaveShare_Mounting|Camera-Mount|Camera-Model|Top-V2/i
/**
 * Extra skips on mobile / lean tier.
 * NEVER skip drive servos (ST3215) or plate standoffs (94868A713) — they are the
 * visual bridge from plate → mount → servo → hub → wheel and layer1 → layer2.
 * Hiding them makes wheels look detached and the torso look like it floats.
 */
const LEKIWI_LEAN_MESH = /Battery---|lipo_battery|servo_controller|Bottom-V2/i
/** Seat the torso on layer2 only — layer1 is the motor deck under the standoffs. */
const KIWI_PLATE_LINKS = ['base_plate_layer2-v3']

function tintMesh(mesh: Mesh, hex: string, roughness = 0.58, metalness = 0.08, doubleSide = false) {
  const lean = getPerfTier().leanMeshes
  mesh.material = new MeshStandardMaterial({
    color: hex,
    roughness,
    metalness: lean ? 0 : metalness,
    flatShading: lean,
    side: doubleSide ? DoubleSide : undefined,
    // Overlapping printable solids (deck ribs, flange lip) z-fight without this.
    polygonOffset: true,
    polygonOffsetFactor: 1,
    polygonOffsetUnits: 1,
  })
  mesh.castShadow = !lean
  mesh.receiveShadow = !lean
}

/** Paint every mesh the colourway primary (whole twin body). */
function colorizeRoot(root: Object3D, colour: Colourway, doubleSide = false) {
  const body = colour.primary
  root.traverse((obj) => {
    const mesh = obj as Mesh
    if (!mesh.isMesh || !mesh.geometry) return
    tintMesh(mesh, body, 0.55, 0.08, doubleSide)
  })
}

function cadHeightMm(geom: BufferGeometry) {
  const b = geom.boundingBox
  if (!b) return 200
  return Math.max(20, b.max.z - b.min.z)
}

function footGeometry(geom: BufferGeometry) {
  const g = geom.clone()
  g.computeBoundingBox()
  const b = g.boundingBox
  if (b) {
    g.translate(-(b.min.x + b.max.x) * 0.5, -(b.min.y + b.max.y) * 0.5, -b.min.z)
  }
  g.computeBoundingBox()
  g.computeVertexNormals()
  return g
}

function usePreparedStl(url: string) {
  const raw = useLoader(STLLoader, url) as BufferGeometry
  return useMemo(() => footGeometry(raw), [raw])
}

function meshLabel(obj: Object3D) {
  const parts: string[] = []
  let p: Object3D | null = obj
  for (let i = 0; i < 8 && p; i++) {
    if (p.name) parts.push(p.name)
    p = p.parent
  }
  return parts.join(' ').toLowerCase()
}

function nearestUrdfLink(obj: Object3D, robot: URDFRobot) {
  let p: Object3D | null = obj
  while (p) {
    if (p.name && robot.links[p.name]) return p.name
    p = p.parent
  }
  return null
}

function isLeKiwiArmMesh(n: string) {
  return (
    n.includes('base_08') ||
    n.includes('so_arm') ||
    n.includes('rotation_pitch_08') ||
    n.includes('wrist') ||
    n.includes('jaw') ||
    n.includes('passive_horn') ||
    n.includes('sts3215_03a') ||
    n.includes('waveshare_mounting_plate_01')
  )
}

function isLeKiwiCamTower(n: string) {
  return n.includes('camera-mount') || n.includes('camera-model') || n.includes('top-v2')
}

function applyLeKiwiVisibility(robot: URDFRobot) {
  robot.traverse((obj) => {
    const mesh = obj as Mesh
    if (!mesh.isMesh) return
    const n = meshLabel(obj)
    if (isLeKiwiCamTower(n) || isLeKiwiArmMesh(n)) {
      mesh.visible = false
      return
    }
    mesh.visible = true
  })
}

function liftT(carriageAglMm: number) {
  const span = TELESCOPE.max_agl_mm - TELESCOPE.min_agl_mm
  return span > 0 ? Math.max(0, Math.min(1, (carriageAglMm - TELESCOPE.min_agl_mm) / span)) : 0
}

function setJoint(robot: URDFRobot, name: string, value: number) {
  if (robot.joints[name]) robot.setJointValue(name, value)
}

function mapSo101Arm(
  robot: URDFRobot,
  carriageAglMm: number,
  armShoulderRad: number,
  armElbowRad: number,
  _side: 'L' | 'R',
) {
  const t = liftT(carriageAglMm)
  // Same pose on both; group yaw (ARM_FORWARD_YAW) points them rover-forward.
  void _side
  setJoint(robot, 'shoulder_pan', 0)
  setJoint(robot, 'shoulder_lift', -0.25 - t * 0.2 + armShoulderRad * 0.35)
  setJoint(robot, 'elbow_flex', 1.0 - t * 0.25 + armElbowRad * 0.4)
  setJoint(robot, 'wrist_flex', -0.15)
  setJoint(robot, 'wrist_roll', 0)
  setJoint(robot, 'gripper', 0.35)
}

function visibleWorldBox(root: Object3D) {
  root.updateWorldMatrix(true, true)
  const box = new Box3()
  let any = false
  root.traverse((obj) => {
    const mesh = obj as Mesh
    if (!mesh.isMesh || !mesh.geometry || !mesh.visible) return
    let p: Object3D | null = obj
    while (p) {
      if (!p.visible) return
      p = p.parent
    }
    const b = new Box3().setFromObject(obj)
    if (Number.isFinite(b.min.y) && Number.isFinite(b.max.y)) {
      box.union(b)
      any = true
    }
  })
  return any ? box : null
}

function meshBoxForLinks(robot: URDFRobot, names: string[]) {
  const want = new Set(names)
  const box = new Box3()
  let any = false
  robot.updateWorldMatrix(true, true)
  robot.traverse((obj) => {
    const mesh = obj as Mesh
    if (!mesh.isMesh || !mesh.visible || !mesh.geometry) return
    const link = nearestUrdfLink(obj, robot)
    if (!link || !want.has(link)) return
    const b = new Box3().setFromObject(obj)
    if (Number.isFinite(b.min.y)) {
      box.union(b)
      any = true
    }
  })
  return any ? box : null
}

/** Zero parent poses while seating so Sim drive/yaw cannot warp AABBs. */
function withIdentityParents(obj: Object3D, fn: () => void) {
  type Saved = { o: Object3D; x: number; y: number; z: number; rx: number; ry: number; rz: number }
  const saved: Saved[] = []
  let p: Object3D | null = obj.parent
  while (p) {
    saved.push({
      o: p,
      x: p.position.x,
      y: p.position.y,
      z: p.position.z,
      rx: p.rotation.x,
      ry: p.rotation.y,
      rz: p.rotation.z,
    })
    p.position.set(0, 0, 0)
    p.rotation.set(0, 0, 0)
    p = p.parent
  }
  obj.updateWorldMatrix(true, true)
  try {
    fn()
  } finally {
    for (const s of saved) {
      s.o.position.set(s.x, s.y, s.z)
      s.o.rotation.set(s.rx, s.ry, s.rz)
    }
    obj.updateWorldMatrix(true, true)
  }
}

function useUrdf(url: string, workingPath: string, skipMesh?: RegExp, leanMesh?: RegExp) {
  const [robot, setRobot] = useState<URDFRobot | null>(null)
  const [generation, setGeneration] = useState(0)
  const [failed, setFailed] = useState(false)

  useEffect(() => {
    let cancelled = false
    let parsed: URDFRobot | null = null
    let meshesDone = false
    let pendingMeshes = 0
    let urdfParsed = false

    const finish = () => {
      if (cancelled || !parsed || !meshesDone || !urdfParsed) return
      // Require at least one real mesh when the URDF requested any.
      let meshCount = 0
      parsed.traverse((obj) => {
        if ((obj as Mesh).isMesh) meshCount++
      })
      if (pendingMeshes > 0 && meshCount === 0) return
      setRobot(parsed)
      setGeneration((g) => g + 1)
    }

    const manager = new LoadingManager()
    manager.onLoad = () => {
      meshesDone = true
      finish()
    }
    manager.onError = (res) => {
      console.error('URDF mesh failed', res)
      if (!cancelled) setFailed(true)
    }
    const loader = new URDFLoader(manager)
    loader.workingPath = workingPath
    loader.parseCollision = false
    loader.parseVisual = true
    const defaultMesh = loader.defaultMeshLoader.bind(loader)
    loader.loadMeshCb = (path, mgr, material, done) => {
      if (skipMesh?.test(path) || leanMesh?.test(path)) {
        done(new Object3D())
        return
      }
      pendingMeshes++
      defaultMesh(path, mgr, material, (scene, err) => {
        pendingMeshes = Math.max(0, pendingMeshes - 1)
        // Clone geometry so L/R arms don't share buffers (missing base on one side).
        // Name meshes from the STL path so seating can find base_so101 (URDF visuals are unnamed).
        if (scene) {
          const leaf = path.split('/').pop()?.replace(/\?.*$/, '') ?? ''
          scene.traverse((obj) => {
            const mesh = obj as Mesh
            if (mesh.isMesh && mesh.geometry) {
              mesh.geometry = mesh.geometry.clone()
              if (leaf) {
                mesh.name = leaf
                mesh.userData.meshFile = leaf
              }
            }
          })
          if (leaf && !scene.name) scene.name = leaf
        }
        done(scene, err)
        if (urdfParsed && pendingMeshes === 0) {
          meshesDone = true
          finish()
        }
      })
    }
    loader.load(
      url,
      (r) => {
        parsed = r
        urdfParsed = true
        // If every mesh was sync-skipped / already loaded, close out.
        queueMicrotask(() => {
          const mgr = manager as LoadingManager & { itemsTotal?: number; itemsLoaded?: number }
          const total = mgr.itemsTotal ?? 0
          const loaded = mgr.itemsLoaded ?? 0
          if (pendingMeshes === 0 && (total === 0 || loaded >= total)) {
            meshesDone = true
            finish()
          }
        })
      },
      undefined,
      (err) => {
        console.error('URDF failed to load', url, err)
        if (!cancelled) setFailed(true)
      },
    )
    return () => {
      cancelled = true
    }
  }, [url, workingPath, skipMesh, leanMesh])

  return { robot, generation, failed }
}

export function WheeledChassis({
  colour,
  carriageAglMm,
  armShoulderRad = 0,
  armElbowRad = 0,
  showWipe = true,
}: {
  colour: Colourway
  carriageAglMm: number
  armShoulderRad?: number
  armElbowRad?: number
  showWipe?: boolean
}) {
  void showWipe
  const perf = useMemo(() => getPerfTier(), [])
  const lekiwiLean = perf.leanMeshes ? LEKIWI_LEAN_MESH : undefined
  const lekiwi = useUrdf(LEKIWI_URDF, LEKIWI_PATH, LEKIWI_SKIP_MESH, lekiwiLean)
  // Separate URLs so each arm gets its own Object3D tree + cloned geometries.
  const so101L = useUrdf(`${SO101_URDF}?side=L`, SO101_PATH)
  const so101R = useUrdf(`${SO101_URDF}?side=R`, SO101_PATH)

  const torsoGeom = usePreparedStl(TORSO_STL)
  const armbaseGeom = usePreparedStl(ARMBASE_STL)
  // Clean printable neck/head — origin-clean HouseHand meshes.
  const neckGeom = usePreparedStl(NECK_STL)
  const headMountGeom = usePreparedStl(HEAD_MOUNT_STL)
  const headCamGeom = usePreparedStl(HEAD_CAM_STL)
  const torsoMm = useMemo(() => cadHeightMm(torsoGeom), [torsoGeom])
  const armMm = useMemo(() => cadHeightMm(armbaseGeom), [armbaseGeom])
  const neckMm = useMemo(() => cadHeightMm(neckGeom), [neckGeom])
  const headMountMm = useMemo(() => cadHeightMm(headMountGeom), [headMountGeom])

  const rootRef = useRef<Group>(null)
  const kiwiRef = useRef<Group>(null)
  const stackRef = useRef<Group>(null)
  const armbaseRef = useRef<Mesh>(null)
  const neckRef = useRef<Mesh>(null)
  const armLRef = useRef<Group>(null)
  const armRRef = useRef<Group>(null)
  const [floorY, setFloorY] = useState(0)
  const [stackPose, setStackPose] = useState({ x: 0, y: 0, z: 0 })
  const [armLPose, setArmLPose] = useState({ x: MOUNT_PAD_X_MM, y: -MOUNT_HALF_MM, z: 0 })
  const [armRPose, setArmRPose] = useState({ x: MOUNT_PAD_X_MM, y: MOUNT_HALF_MM, z: 0 })
  const [neckZ, setNeckZ] = useState(0)
  const [revealed, setRevealed] = useState(false)

  const assembled = !!(lekiwi.robot && so101L.robot && so101R.robot)
  const loading =
    (!lekiwi.robot && !lekiwi.failed) ||
    (!so101L.robot && !so101L.failed) ||
    (!so101R.robot && !so101R.failed)

  useLayoutEffect(() => {
    if (!lekiwi.robot) return
    applyLeKiwiVisibility(lekiwi.robot)
    colorizeRoot(lekiwi.robot, colour)
  }, [lekiwi.robot, lekiwi.generation, colour])

  useLayoutEffect(() => {
    if (!so101L.robot) return
    colorizeRoot(so101L.robot, colour)
    mapSo101Arm(so101L.robot, carriageAglMm, armShoulderRad, armElbowRad, 'L')
  }, [so101L.robot, so101L.generation, colour, carriageAglMm, armShoulderRad, armElbowRad])

  useLayoutEffect(() => {
    if (!so101R.robot) return
    colorizeRoot(so101R.robot, colour)
    mapSo101Arm(so101R.robot, carriageAglMm, armShoulderRad, armElbowRad, 'R')
  }, [so101R.robot, so101R.generation, colour, carriageAglMm, armShoulderRad, armElbowRad])

  useLayoutEffect(() => {
    const root = rootRef.current
    const kiwiG = kiwiRef.current
    const stack = stackRef.current
    const armL = armLRef.current
    const armR = armRRef.current
    if (!root) return

    withIdentityParents(root, () => {
      root.position.y = 0
      if (stack) stack.position.set(0, 0, 0)
      root.updateWorldMatrix(true, true)

      const kiwiBox = kiwiG ? visibleWorldBox(kiwiG) : null
      const nextFloor = kiwiBox ? -kiwiBox.min.y + SIT_EPS : 0
      root.position.y = nextFloor
      root.updateWorldMatrix(true, true)

      const plateBox = lekiwi.robot ? meshBoxForLinks(lekiwi.robot, KIWI_PLATE_LINKS) : null
      const plateCx = plateBox ? (plateBox.min.x + plateBox.max.x) * 0.5 : 0
      const plateCz = plateBox ? (plateBox.min.z + plateBox.max.z) * 0.5 : 0
      const plateTop = plateBox?.max.y ?? kiwiBox?.max.y ?? nextFloor

      const nextStack = {
        x: plateCx,
        y: plateTop - SIT_EPS - nextFloor,
        z: plateCz,
      }
      if (stack) stack.position.set(nextStack.x, nextStack.y, nextStack.z)

      // Arms in the same mm print frame as the shoulder deck → sit on pad tops.
      const padZ = torsoMm + SHOULDER_PAD_TOP_MM
      const nextArmL = { x: MOUNT_PAD_X_MM, y: -MOUNT_HALF_MM, z: padZ }
      const nextArmR = { x: MOUNT_PAD_X_MM, y: MOUNT_HALF_MM, z: padZ }
      if (armL) {
        armL.rotation.set(0, 0, ARM_FORWARD_YAW)
        armL.position.set(nextArmL.x, nextArmL.y, nextArmL.z)
        armL.scale.set(ARM_IN_PRINT, ARM_IN_PRINT, ARM_IN_PRINT)
      }
      if (armR) {
        armR.rotation.set(0, 0, ARM_FORWARD_YAW)
        armR.position.set(nextArmR.x, nextArmR.y, nextArmR.z)
        armR.scale.set(ARM_IN_PRINT, ARM_IN_PRINT, ARM_IN_PRINT)
      }
      if (so101L.robot) {
        so101L.robot.position.set(0, 0, 0)
        so101L.robot.rotation.set(0, 0, 0)
        so101L.robot.scale.set(1, 1, 1)
        mapSo101Arm(so101L.robot, carriageAglMm, armShoulderRad, armElbowRad, 'L')
      }
      if (so101R.robot) {
        so101R.robot.position.set(0, 0, 0)
        so101R.robot.rotation.set(0, 0, 0)
        so101R.robot.scale.set(1, 1, 1)
        mapSo101Arm(so101R.robot, carriageAglMm, armShoulderRad, armElbowRad, 'R')
      }

      // Seat neck on the shoulder deck (clean printable — sit flush, no lattice sink hack).
      let nextNeckZ = torsoMm + armMm
      const neckMesh = neckRef.current
      const armbaseMesh = armbaseRef.current
      if (neckMesh && armbaseMesh) {
        for (let i = 0; i < 4; i++) {
          neckMesh.position.set(0, 0, nextNeckZ)
          root.updateWorldMatrix(true, true)
          const armBox = new Box3().setFromObject(armbaseMesh)
          const neckBox = new Box3().setFromObject(neckMesh)
          if (!Number.isFinite(armBox.max.y) || !Number.isFinite(neckBox.min.y)) break
          const gap = neckBox.min.y - armBox.max.y
          if (Math.abs(gap) < 1e-4) break
          nextNeckZ -= gap / PRINT_SCALE
        }
        neckMesh.position.set(0, 0, nextNeckZ)
      }

      if (lekiwi.robot) colorizeRoot(lekiwi.robot, colour)
      if (so101L.robot) colorizeRoot(so101L.robot, colour)
      if (so101R.robot) colorizeRoot(so101R.robot, colour)

      setFloorY((y) => (Math.abs(y - nextFloor) > 1e-4 ? nextFloor : y))
      setStackPose((prev) =>
        Math.abs(prev.x - nextStack.x) > 1e-4 ||
        Math.abs(prev.y - nextStack.y) > 1e-4 ||
        Math.abs(prev.z - nextStack.z) > 1e-4
          ? nextStack
          : prev,
      )
      setArmLPose((prev) =>
        Math.abs(prev.x - nextArmL.x) > 1e-4 ||
        Math.abs(prev.y - nextArmL.y) > 1e-4 ||
        Math.abs(prev.z - nextArmL.z) > 1e-4
          ? nextArmL
          : prev,
      )
      setArmRPose((prev) =>
        Math.abs(prev.x - nextArmR.x) > 1e-4 ||
        Math.abs(prev.y - nextArmR.y) > 1e-4 ||
        Math.abs(prev.z - nextArmR.z) > 1e-4
          ? nextArmR
          : prev,
      )
      setNeckZ((z) => (Math.abs(z - nextNeckZ) > 1e-3 ? nextNeckZ : z))
      setRevealed(true)
    })
  }, [
    lekiwi.robot,
    so101L.robot,
    so101R.robot,
    lekiwi.generation,
    so101L.generation,
    so101R.generation,
    torsoMm,
    armMm,
    neckMm,
    carriageAglMm,
    armShoulderRad,
    armElbowRad,
    colour,
  ])

  useEffect(() => {
    if (!assembled) setRevealed(false)
  }, [assembled])

  const shadows = !perf.leanMeshes
  const neckSeatZ = neckZ || torsoMm + armMm
  const headZ = neckSeatZ + neckMm
  const camZ = headZ + headMountMm

  return (
    <group>
      <group ref={rootRef} position={[0, floorY, 0]} visible={revealed}>
        {lekiwi.robot ? (
          <group ref={kiwiRef} rotation={ROS_TO_THREE}>
            <primitive object={lekiwi.robot} />
          </group>
        ) : null}

        {assembled ? (
          <group ref={stackRef} rotation={STACK_TO_THREE} position={[stackPose.x, stackPose.y, stackPose.z]}>
            {/* Printables + arms share the mm frame so pads and mounts coincide. */}
            <group scale={PRINT_SCALE}>
              <mesh geometry={torsoGeom} castShadow={shadows} receiveShadow={shadows}>
                <meshStandardMaterial
                  color={colour.primary}
                  roughness={0.55}
                  metalness={0.08}
                  polygonOffset
                  polygonOffsetFactor={1}
                  polygonOffsetUnits={1}
                />
              </mesh>

              <mesh
                ref={armbaseRef}
                geometry={armbaseGeom}
                position={[0, 0, torsoMm]}
                castShadow={shadows}
                receiveShadow={shadows}
              >
                <meshStandardMaterial
                  color={colour.primary}
                  roughness={0.5}
                  metalness={0.1}
                  polygonOffset
                  polygonOffsetFactor={1}
                  polygonOffsetUnits={1}
                />
              </mesh>

              <mesh
                ref={neckRef}
                geometry={neckGeom}
                position={[0, 0, neckSeatZ]}
                castShadow={shadows}
                receiveShadow={shadows}
              >
                <meshStandardMaterial
                  color={colour.primary}
                  roughness={0.52}
                  metalness={0.1}
                  polygonOffset
                  polygonOffsetFactor={1}
                  polygonOffsetUnits={1}
                />
              </mesh>

              <mesh
                geometry={headMountGeom}
                position={[0, 0, headZ]}
                castShadow={shadows}
                receiveShadow={shadows}
              >
                <meshStandardMaterial color={colour.primary} roughness={0.45} metalness={0.12} />
              </mesh>
              <mesh
                geometry={headCamGeom}
                position={[0, 25, camZ + 18]}
                rotation={[Math.PI / 2, 0, 0]}
                castShadow={shadows}
                receiveShadow={shadows}
              >
                <meshStandardMaterial color={colour.primary} roughness={0.4} metalness={0.15} />
              </mesh>

              <group
                ref={armLRef}
                position={[armLPose.x, armLPose.y, armLPose.z]}
                rotation={[0, 0, ARM_FORWARD_YAW]}
                scale={[ARM_IN_PRINT, ARM_IN_PRINT, ARM_IN_PRINT]}
              >
                <primitive key={`arm-L-${so101L.generation}`} object={so101L.robot!} />
              </group>
              <group
                ref={armRRef}
                position={[armRPose.x, armRPose.y, armRPose.z]}
                rotation={[0, 0, ARM_FORWARD_YAW]}
                scale={[ARM_IN_PRINT, ARM_IN_PRINT, ARM_IN_PRINT]}
              >
                <primitive key={`arm-R-${so101R.generation}`} object={so101R.robot!} />
              </group>
            </group>
          </group>
        ) : null}
      </group>

      {loading || !revealed ? (
        <mesh position={[0, 0.32, 0]}>
          <boxGeometry args={[0.16, 0.42, 0.16]} />
          <meshStandardMaterial color="#64748b" wireframe transparent opacity={0.5} />
        </mesh>
      ) : null}
    </group>
  )
}

export function meshAttribution(kit: KitBuild) {
  return (
    `${kitCaption(kit)}. ` +
    `LeKiwi kit mobile base (SIGRobotics-UIUC) · HouseHand torso/deck/neck/head · ` +
    `2× SO-101 (TheRobotStudio), Apache-2.0. ` +
    `Stack: LeKiwi plate → HouseHand_torso → shoulder_deck → SO-101s → neck → head. ` +
    `No IKEA RÅSKOG cart. Print kit: print/README.md.`
  )
}

export const MESH_ATTRIBUTION = meshAttribution({
  preset: 'xlerobot',
  base: 'lekiwi',
  arms: 'xlerobot',
  head: 'xlerobot',
})
